services:
  mysqldb:
    image: mysql:5.7
    container_name: mysqldb
    restart: unless-stopped
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: herU@1234
      MYSQL_DATABASE: sep
      MYSQL_USER: admin
      MYSQL_PASSWORD: herU@1234
      SERVICE_TAGS: dev
      SERVICE_NAME: mysqldb
    ports:
      - 3306:3306
    
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/0_init.sql
      - $HOME/database:/var/lib/mysql
    expose:
      - 3306
    networks:
      - sep-network
  nodejs:
    image: node
    container_name: nodejs
    restart: always
    build: .
    ports:
      - 3005:3005
    environment:
      PORT: 3005
      DB_PORT: 3306
      DB_USER: 'admin'
      DB_PASSWORD: 'herU@1234'
      DB_DB: 'sep'
      DB_HOST: mysqldb
    command: npm run dev
    expose:
      - 3005
    networks:
      - sep-network
    depends_on:
      - mysqldb
networks:
  sep-network:
    driver: bridge