CREATE DATABASE IF NOT EXISTS SEP;

USE SEP;

CREATE TABLE IF NOT EXISTS EMPLOYEES (
    ID VARCHAR(255) PRIMARY KEY,
    NAME VARCHAR(255),
    SALARY DECIMAL(10, 2),
    POSITION VARCHAR(255),
    JOIN_DATE DATE
)
