CREATE DATABASE IF NOT EXISTS sep;

USE sep;

CREATE TABLE IF NOT EXISTS employees (
    ID VARCHAR(255) PRIMARY KEY,
    NAME VARCHAR(255),
    SALARY DECIMAL(10, 2),
    POSITION VARCHAR(255),
    JOIN_DATE DATE
)
